config/routes.rb
Pushmedic::Application.routes.draw do

  root to: 'home#index'

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match "/contact"  => "home#contact",  :as => "contact",   :via => :get
  match "/about"    => "home#about",    :as => "about",     :via => :get
  match "/product"  => "home#product",  :as => "product",   :via => :get
  match "/product/:id"  => "home#product_show", :as => "product_show", :via => :get
  match "/send_message" => "home#send_message", :as => "send_message", :via => :post

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :body, :email, :name, :phone

  validates :body, :email, :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :title, :image, :product_type_id
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, :product_type_id, presence: true

  belongs_to :product_type

  has_attached_file :image, :styles => {big: "637x419>", medium: "306x168>", thumb: "52x38>" },
                    :default_url => "/images/:style/missing.png"
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }

end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  attr_accessible :name

  has_many :products

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :role

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end

  def product
    @products = Product.all
    @type = ProductType.all
  end

  def product_show
    @product = Product.find(params[:id])
    @random_product = Product.all.sample(10)
  end

  def contact
    @message = Message.new
  end

  def send_message
    name = params[:message][:name]
    phone = params[:message][:phone]
    email = params[:message][:email]
    message = params[:message][:body]
    if params[:message][:body].present?
      Message.create(params[:message])
      #UserMailer.contact_us(name, email, phone, message).deliver
      flash[:notice] = "your message has been sent, we will review and reply your message soon."
      redirect_to contact_path
    else

    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<%= content_for :page_head do %>
  <hgroup class="page-head">
	<h2>About <span>PUSHMEDIC</span></h2>
	<h5>We are an integrated IT solution company, located in Bandung - Indonesia, which delivers services in software development, IT infrastructure, creative strategy and digital marketing. We are consists of creative talents which already experienced in developing enterprise application and also providing consultation in the area of IT services and digital marketing to several big corporate in Indonesia.</h5>
	<br />
	<h5>Our specialties are software development, web design, android app development, IOS app development, UI + UX design, IT infrastructure, and digital marketing. With those specialties, we hope to give our customers to succeed over their competition.</h5>
  </hgroup>
<% end %>

<div id="content" class="full-width">

  <h3>Here the reason why you must Pushjaw</h3>
  <div class="accordion">
	<h5 class="current"><span></span>1. Latest Technology</h5>
	<div class="pane current">
	  By using the latest technology, you are getting the best possible results when it comes to your website design, and by adhering to industry standards we ensure your site will work everywhere, on anything.
	</div>
	<h5 class=""><span></span>2. Professional Team</h5>
	<div class="pane ">
	  We have professional, hard-working and high skilled team. Our team always brings innovative ideas to give excellent results to all clients globally
	</div>
	<h5 class=""><span></span>3. Reliable Support</h5>
	<div class="pane ">
	  we’re well suited to provide reliable, quality support to clients of all types. We have a firm belief in being part of our clients’ teams and we’re prepared to go above and beyond to do it.
	</div>
  </div>

  <h3>PUSHJAWER's</h3>
  <blockquote>
	<p>A Rock development teams.</p>
  </blockquote>

</div>

app/views/home/contact.html.erb
<%= content_for :page_head do %>
  <hgroup class="page-head">
	<h2>Contact <span>Us</span></h2>
	<h5></h5>
  </hgroup>
<% end %>

<% if flash[:notice] %>
  <p class="info">
	<%= flash[:notice] %>
  </p>
<% end %>

<div id="content">
  <div class="map-container clearfix">
	<div id="map_canvas"></div>
  </div>

  <section class="widget">
	<h3 class="title quick-call">Quick Contact</h3>
	<div class="contact-widget">
	  <p>
		<strong>Work    :</strong> +62 226001425<br>
		<strong>Cell    :</strong> +62 226001425<br>
		<strong>Support :</strong> ahmadfirman88@gmail.com<br>
	  </p>
	  <hr>
	</div>

	<h3 class="title quick-call">Our Address</h3>
	<div class="contact-widget">
	  <p>
		<strong>Kompleks Melong Green Garden / Jalan Mig 3 No. 1</strong><br>
		<strong>Cimahi, Jawa Barat, Indonesia</strong><br>
		<strong>(6222) 6001425 / ahmadfirman88@gmail.com</strong><br>
	  </p>
	  <hr>
	</div>
  </section>
  <p></p>

</div>

<aside id="sidebar">
  <section class="widget">
	<div class="appointment">
	  <div class="header">
		<h2>Make an Appointment</h2>
		<h3 class="number">+62 226001425</h3>
		<span class="or">OR</span>
	  </div>
	  <%= form_for(@message, url: send_message_path, html: {id: "appoint-form", novalidate: "novalidate"}) do |f| %>
	  	<p>
		  <label class="display-ie8" for="apo_name">Full Name</label>
		  <%= f.text_field :name, class: "required", placeholder: "Full Name", title: "* Please enter your Full Name" %>
		</p>
		<p>
		  <label class="display-ie8" for="apo_phone">Phone Number</label>
		  <%= f.text_field :phone, class: "required", placeholder: "Phone Number", title: "* Please enter your Phone Number" %>
		</p>
		<p>
		  <label class="display-ie8" for="apo_email">Email Address</label>
		  <%= f.text_field :email, class: "email required", placeholder: "Email Address", title: "* Please enter valide Email Address" %>
		</p>
		<p>
		  <label class="display-ie8" for="apo_date">Message</label>
		  <%= f.text_area :body, class: "message required", cols: "30", rows: "5", placeholder: "Message", title: "* Please enter your message" %>
		</p>

		<p>
		  <input type="submit" value="Submit Request" class="readmore">
		  <img src="/assets/loading.gif" id="apo-loader" alt="Loader">
		</p>
		<p id="apo-message-sent"></p>
		<div class="error-container"></div>
	  <% end %>
	</div>
  </section>
</aside>


<%= content_for :javascripts do %>
  <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
  <script type="text/javascript">

	function initialize()
	{
	  var geocoder  = new google.maps.Geocoder();
	  var map;
	  var latlng = new google.maps.LatLng(-6.9227569, 107.5632968);
	  var infowindow = new google.maps.InfoWindow();
	  var myOptions = {
		zoom: 15,
		mapTypeId: google.maps.MapTypeId.ROADMAP
	  };

	  map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

	  geocoder.geocode( { 'location': latlng },
			  function(results, status) {
				if (status == google.maps.GeocoderStatus.OK)
				{
				  map.setCenter(results[0].geometry.location);
				  var marker = new google.maps.Marker({
					map: map,
					position: results[0].geometry.location
				  });
				}
				else
				{
				  alert("Geocode was not successful for the following reason: " + status);
				}
			  });
	}
	initialize();

  </script>

<% end %>

app/views/home/index.html.erb
<%= content_for :slider do %>
  <div id="slider-wrap">
	<div class="flexslider">
	  <ul class="slides">
		<li>
		  <a href="#" title="Qualified Doctors"  class="img-hover" ><img src="/assets/products/charts.png" alt="Slider Image"></a>
		</li>
		<li>
		  <a href="#" title="Clinical Excellence"  class="img-hover" ><img src="/assets/products/services.png" alt="Slider Image"></a>
		</li>
		<li>
		  <a href="#" title="Dental Treatment"  class="img-hover" ><img src="/assets/products/pharmacy.png" alt="Slider Image"></a>
		</li>
		<li>
		  <a href="#" title="Caring Staff"  class="img-hover" ><img src="/assets/products/accounting.png" alt="Slider Image"></a>
		</li>
		<li>
		  <a href="#" title="Medical Counseling"  class="img-hover" ><img src="/assets/products/report.png" alt="Slider Image"></a>
		</li>
	  </ul>
	  <ul class="slide-nav slides-5">
		<li>
		  <h4>Charts</h4>
		  <p>Team of Expert Doctors</p>
		</li>
		<li>
		  <h4>Services</h4>
		  <p>Expert in Clinical Work</p>
		</li>
		<li>
		  <h4>Pharmacy</h4>
		  <p>Specialized in Dental Care</p>
		</li>
		<li>
		  <h4>Accounting</h4>
		  <p>Caring Staff</p>
		</li>
		<li>
		  <h4>Report</h4>
		  <p>Discuss Your Health</p>
		</li>
	  </ul><!-- end of slider nav -->
	</div>
  </div>
<% end %>

app/views/home/product.html.erb
<%= content_for :page_head do %>
  <hgroup class="page-head">
	<h2>Our <span>PRODUCT</span></h2>
	<h5></h5>
  </hgroup>
<% end %>

<div id="content" class="full-width" style="min-height: 200px;">

  <ul id="filter-by" class="clearfix">
	<li><a href="#" data-filter="gallery-item" class="active">All</a></li>
	<% @type.each do |type| %>
	  <li><a href="#" data-filter="<%= type.id %>" title="View all Gallery Items filed under <%= type.name %>"><%= type.name %></a></li>
	<% end %>
  </ul>

  <div id="gallery-container" class="gallery-3-columns isotope clearfix">
	<% @products.each do |product| %>
	  <div class="type-gallery-item gallery-item isotope-item <%= product.product_type_id %> ">
		<a class="pretty-photo" href="<%= product.image(:big) %>">
		  <%= image_tag(product.image(:medium), size: "306x168", alt: product.title) %>
		</a>
		<h5 class="item-title"><%= truncate(product.description, length: 45) %></h5>
		<span class="item-type-link">
		  <%= link_to product.title, product_show_path(product) %>
		</span>
	  </div>
	<% end %>
  </div>

</div>

app/views/home/product_show.html.erb
<hgroup class="page-head">
  <h2>Product <span><%= @product.title %></span></h2>
  <h5>Lorem ipsum dolor sit amet, consectetuer </h5>
</hgroup>

<div id="container" class="clearfix">

<div id="content">
  <article id="post-example" class="hentry clearfix">

	<header>
	  <h1 class="post-title">
		<a href="#"><%= @product.title.titleize %></a>
	  </h1>

	  <div class="post-thumb">
		<a href="<%= @product.image(:big) %>" title="Latest Health Lessons" class="pretty-photo">
		  <%= image_tag(@product.image(:big), alt: @product.title ) %>
		</a>
	  </div>

	</header>

	<p><%= @product.description %></p>

  </article>

</div>

<aside id="sidebar">

  <section class="widget">
	<h3 class="title">Recent Items</h3>

	<div class="sidebar-post clearfix">
	  <% @random_product.each do |random| %>
		<div style="clear: both;">
		  <%= link_to product_show_path(random) do %>
			<%= image_tag(random.image(:thumb), size: "52x38") %>
		  <% end %>
		  <div class="sidebar-post-text">
			<%= link_to random.title, product_show_path(random) %>
			<span class="date"><%= random.updated_at.strftime("%B %d, %Y ") %></span>
		  </div>
		</div>
	  <% end %>
	</div>

  </section>

</aside>

</div>

app/views/home/send_message.js.erb
$('#apo-loader').hide();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 7]>    <html class="ie7" > <![endif]-->
<!--[if IE 8]>    <html class="ie8" > <![endif]-->
<!--[if IE 9]>    <html class="ie9" > <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en-US"> <!--<![endif]-->
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width" />
  <title>Pushmedic</title>

  <!-- FAVICON -->
  <link rel="shortcut icon" href="/assets/favicon.png.png" />

  <!-- Style Sheet-->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,800,700,300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag :application %>

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="/assets/html5.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>

<body>

  <div id="wrapper">

	<header id="header">
	  <%= render partial: "/shared/header" %>
	</header>

	<%= yield :slider %>
	<%= yield :page_head %>

	<div id="container" class="clearfix">
	  <%= yield %>
	  <div id="content" class="full-width"></div>
	</div>

	<div id="footer-bottom-wrapper">
	  <div id="footer-bottom">
		<p class="copyrights">© Copyright 2012. All Rights Reserved by pushjaw.com</p>
	  </div>
	</div>

  </div>

  <%= javascript_include_tag :application %>
  <%= yield :javascripts %>
  <a href="#top" id="scroll-top"></a>

</body>
</html>

app/views/shared/_header.html.erb
<!-- Website Logo Place -->
<div id="logo-container">
  <a href="index.html" class="logo"  title="Pushmedic">
	<img src="/assets/pushmedic-logo.png" size="20x20" alt="PUSHMEDIC">
  </a>
</div>

<ul class="social-nav">
  <li class="facebook"><a target="_blank" href="#"></a></li>
  <li class="twitter"><a target="_blank" href="#"></a></li>
  <li class="skype"><a target="_blank" href="#"></a></li>
  <li class="google"><a target="_blank" href="#"></a></li>
  <li class="phone"><span> +62 226001425</span></li>
</ul>

<nav class="main-nav clearfix">

  <div class="menu-div">
	<ul>
	  <li><%= link_to "Home", root_path %></li>
	  <li><%= link_to "About Us", about_path %></li>
	  <li><%= link_to "Product", product_path %></li>
	  <li><%= link_to "Contact Us", contact_path %></li>
	</ul>
  </div>

  <form method="get" action="#" id="topsearch">
	<p>
	  <input type="text" placeholder="Search" name="s" id="tsearch">
	  <input type="submit" id="topsubmit" value="">
	</p>
  </form>
</nav>

app/views/simple_captcha/_simple_captcha.erb
<style type="text/CSS">
  .simple_captcha{border: 1px solid #ccc; padding: 5px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 165px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 12px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>
  
  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>
  
  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>
</div>